#!/bin/bash

echo "📤 推送代码到 GitHub"
echo "======================================"
echo ""
echo "请将下面的 YOUR_GITHUB_USERNAME 替换为你的 GitHub 用户名："
echo ""
echo "1. 添加远程仓库："
echo "   git remote add origin https://github.com/YOUR_GITHUB_USERNAME/ancient-tree-app.git"
echo ""
echo "2. 重命名分支："
echo "   git branch -M main"
echo ""
echo "3. 推送代码："
echo "   git push -u origin main"
echo ""
echo "🔑 如果提示输入密码，请使用："
echo "   - GitHub 个人访问令牌（推荐）"
echo "   - 或 GitHub 密码"
echo ""
echo "💡 如何创建个人访问令牌："
echo "   1. 访问 https://github.com/settings/tokens"
echo "   2. 点击 'Generate new token'"
echo "   3. 选择 'repo' 权限"
echo "   4. 复制生成的令牌作为密码"