#!/bin/bash

echo "🚀 最简单推送方法"
echo "======================================"
echo ""

echo "📋 复制并执行以下命令："
echo ""
echo "1. 进入项目目录："
echo "   cd /root/.openclaw/workspace/mobileapp/MyMobileApp"
echo ""
echo "2. 设置 HTTPS 远程仓库："
echo "   git remote remove origin 2>/dev/null || true"
echo "   git remote add origin https://github.com/likan19841106/ancient-tree-app.git"
echo ""
echo "3. 推送代码（会提示输入凭证）："
echo "   git push -u origin main"
echo ""
echo "🔐 身份验证时输入："
echo "   Username: likan19841106"
echo "   Password: 你的新 Token（有 repo + workflow 权限）"
echo ""
echo "📊 成功后访问："
echo "   https://github.com/likan19841106/ancient-tree-app/actions"
echo ""
echo "⏳ 构建时间: 10-15分钟"
echo "📱 下载 APK 文件安装到手机"